In [39]:
# # !pip install numpy
# !pip install pandas
# !pip install matplotlib
!pip install -U scikit-learn


You should consider upgrading via the 'c:\users\rahul.chatterjee\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [47]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd




In [49]:
dataset=pd.read_csv("Data.csv")
X=dataset.iloc[ : , :-1  ].values
y=dataset.iloc[:, -1]
print(X)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object


# TAKING  CARE  OF  MISSING  DATA

In [56]:
imputer=SimpleImputer(missing_values=np.nan,strategy="mean")
imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])

print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# ENCODING THE DEPENDENT VARIABLE

In [63]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [67]:
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X=np.array(ct.fit_transform(X))
print(X)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


# ENCODING WITH DEPENDENT VARIABLE

In [71]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


# SPLITTING THE DATA SET INTO  THE TRAINING SET AND TEST SET


In [74]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)


In [76]:
print(X_train)

[[1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]


In [80]:
print(X_test)

[[1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [81]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [82]:
print(y_test)

[0 1]


# FEATURE SCALING

In [84]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[:,3:]=sc.fit_transform(X_train[:,3:])
X_test[:,3:]=sc.transform(X_test[:,3:])

In [85]:
print(X_train)

[[1.0 0.0 0.0 1.2909944487358058 -0.1915918438457856 -1.0781259408412427]
 [1.0 0.0 1.0 -0.7745966692414835 -0.014117293757057902
  -0.07013167641635401]
 [0.0 1.0 0.0 -0.7745966692414835 0.5667085065333239 0.6335624327104546]
 [1.0 0.0 0.0 1.2909944487358058 -0.3045301939022488 -0.30786617274297895]
 [1.0 0.0 0.0 1.2909944487358058 -1.901801144700799 -1.4204636155515822]
 [0.0 1.0 0.0 -0.7745966692414835 1.1475343068237056 1.2326533634535488]
 [1.0 0.0 1.0 -0.7745966692414835 1.4379472069688966 1.5749910381638883]
 [0.0 1.0 0.0 -0.7745966692414835 -0.7401495441200352 -0.5646194287757336]]


In [86]:
print(X_test)

[[1.0 0.0 1.0 -0.7745966692414835 -1.4661817944830127 -0.9069571034860731]
 [0.0 1.0 0.0 -0.7745966692414835 -0.44973664397484425
  0.20564033932253029]]
