In [19]:
import numpy as np

In [20]:
arr_1d=np.array([1,2,3])

In [29]:
print(arr_1d)

[1 2 3]


In [30]:
type(arr_1d) #type of array

numpy.ndarray

In [31]:
arr_1d.ndim #finding the dimension of an array

1

In [32]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)
arr_2d.ndim

[[1 2 3 4]
 [5 6 7 8]]


2

In [33]:
print(arr_1d.size)
print(arr_2d.size) 
# find the size or how many elements in an array

3
8


In [34]:
print(arr_1d.shape)
print(arr_2d.shape)
# find the shape or rows and column in an array

(3,)
(2, 4)


In [35]:
print(arr_1d.dtype)
print(arr_2d.dtype)
# checkinf the datatype of the array

int32
int32


In [36]:
arr_2d.dtype

dtype('int32')

In [37]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])