In [6]:
import numpy as np


# arange()

In [3]:
arr1=np.arange(1,13)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [5]:
arr2=np.arange(1,13,2)
print(arr2)

[ 1  3  5  7  9 11]


# linespace()

In [12]:
arr3=np.linspace(1,5,4)
print(arr3)
print(type(arr3))

[1.         2.33333333 3.66666667 5.        ]
<class 'numpy.ndarray'>


# reshape()

In [22]:
arr_2d=arr1.reshape(12,1)
print(arr_2d)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [24]:
arr_3d=arr1.reshape(2,3,2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [28]:
ar=np.arange(1,13).reshape(2,3,2)
print(ar)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# ravel() function convert 1d array to 2 dimensional array

In [30]:
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten()

In [32]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose()

In [42]:
num=np.arange(1,13).reshape(2,6)
arr9=np.transpose(num)
print(arr9)

[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]
