# Mathematic operation using NumPy

In [2]:
import numpy as np

In [6]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# adding two array in one using numpy

In [8]:
arr3=np.add(arr1,arr2)
print(arr3)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]



# subtract two array in numpy

In [10]:
arr4=np.subtract(arr1,arr2)
print(arr4)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


# divide two array in numpy

In [12]:
np.divide(arr1,arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# multiplication of two array in numpy

In [16]:
np.multiply(arr1,arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [18]:
arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [20]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
print("maximum value is ",arr1.max())
print("minimum value is ",arr1.min())

maximum value is  9
minimum value is  1


In [31]:
print("max index number :",arr1.argmax())
print("min index number :",arr1.argmin())

max index number : 8
min index number : 0


In [32]:
print("maximum values in column ",arr1.max(axis=0))
print("min value in column ",arr1.min(axis=0))

maximum values in column  [7 8 9]
min value in column  [1 2 3]


In [33]:
print("max value in row is ",arr1.max(axis=1))
print("min value in row is ",arr1.min(axis=1))

max value in row is  [3 6 9]
min value in row is  [1 4 7]


In [36]:
 print("sum of the array 1 :",np.sum(arr1))

sum of the array 1 : 45


In [40]:
print("sum of the column in array :",np.sum(arr1, axis=0))
print("sum of the row in array :",np.sum(arr1, axis=1))

sum of the column in array : [12 15 18]
sum of the row in array : [ 6 15 24]


In [42]:
print("mean of array1 :",np.mean(arr1))
print("square root of array1 :",np.mean(arr1))

mean of array1 : 5.0
square root of array1 : 5.0


In [44]:
np.std(arr1) # standard division

2.581988897471611

In [46]:
np.exp(arr1)  #expontional 

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [48]:
np.log(arr1) #logirathm of array 1

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [49]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])