In [2]:
import numpy as np

In [4]:
arr1=np.ones(5)
print(arr1)

[1. 1. 1. 1. 1.]


In [6]:
arr2=np.ones((3,3))
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
arr3=np.ones((3,3),dtype=int)
print(arr3)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [9]:
np.ones()

dtype('int32')

In [14]:
arr4=np.zeros((2,3),dtype=int)
print(arr4)

[[0 0 0]
 [0 0 0]]


In [16]:
arr5=np.zeros((2,3),dtype=str)
print(arr5)

[['' '' '']
 ['' '' '']]


In [21]:
arr6=""
print(bool(arr6))

False
